Repository FireCubeStudios/Protecc, pull requests merged in 2022-10, with the labels that each got.

#40 Optimiza README
  README.md
Labels: hacktoberfest-accepted

#41 Feature: Copy code to clipboard by double clicking AccountControl
  TemplateApp/Controls/AccountControl.xaml
  TemplateApp/Controls/AccountControl.xaml.cs
  TemplateApp/MainPage.xaml
Labels: enhancement

#51 Added CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: hacktoberfest-accepted

#50 Create Readme_German.md
  Readme/Readme_German.md
Labels: hacktoberfest-accepted

#52 hindi translation of readme.md
  Readme/readme_hindi.md
Labels: hacktoberfest-accepted

#56 Add Romanian Readme
  Readme/README_Romanian.md
Labels: hacktoberfest-accepted

#57 Added README.ru-RU.md
  Readme/README.ru-RU.md
Labels: hacktoberfest-accepted

#54 Adding Read Me in Punjabi
  Readme/readme_Punjabi.md
Labels: hacktoberfest-accepted

#53 Added Contributing.md
  CODE_OF_CONDUCT.md
  Contributing.md
Labels: hacktoberfest-accepted

#59 Edit existing accounts
  Readme/README.ru-RU.md
  TemplateApp/Controls/AccountControl.xaml
  TemplateApp/Controls/AccountControl.xaml.cs
  TemplateApp/EditAccountPage.xaml
  TemplateApp/EditAccountPage.xaml.cs
  TemplateApp/Helpers/DataHelper.cs
  TemplateApp/Services/CredentialService.cs
Labels: hacktoberfest-accepted, amazing, pending

#55 Improved Placement of Copyright Logo and added discussion Link
  Assets/Get_it_from_Microsoft_Badge.svg
  README.md
  Readme/README.ru-RU.md
  Readme/README.zh-CN.md
  Readme/README_Romanian.md
  Readme/README_Spanish.md
  Readme/Readme_German.md
  Readme/Readme_Hindi.md
Labels: pending

#60 #44 Created README_Norwegian.md
  Readme/README_Norwegian.md
Labels: hacktoberfest-accepted, amazing

#63 improve readme
  README.md
Labels: hacktoberfest-accepted

#67 improve readme
  README.md
  Readme/README.zh-CN.md
Labels: hacktoberfest-accepted
